### ISSUE TITLE
Feedback for 11조

### ISSUE THREAD

**Issue by bewisesh91** [ooommma/team11#22]
### 기본 요구 사항
1. TMDB 또는 영화진흥위원회 오픈 API 이용(택 1 또는 중복 사용)
2. 영화정보 상세 페이지 구현
3. 상세 페이지 영화 리뷰 작성 기능 구현
4. github PR(=Pull Request) 사용한 협업
5. UX를 고려한 validation check
6. Javascript 문법 요소를 5개 이상 이용하여 구현

### 선택 요구 사항
1. flex 사용하기
2. grid 사용하기
3. 반응형 UI 구성하기
4. 상세페이지 리뷰 수정 및 삭제 기능 구현
5. 조건에 맞는 카드 리스트 정렬 기능(이름순, 별점순 등 자유롭게)
6. 위에서 설명하지 않은 기타 외부 Api

### 피드백
기본 요구 사항과 선택 요구 사항을 잘 충족하여 구현한 것 같습니다.
우선, 깃 사용과 관련하여 코멘트를 드리자면, Commit 이력이나 PR을 잘 관리한 것 같아요.
다만, 일부 Commit 중 전체적인 이력과 일관성이 떨어지는 부분(갑자기 한글로 작성하거나 prefix가 없는 경우)이 있습니다. 
PR 역시 리뷰어를 지정하고 해당 리뷰어가 승인한 코드가 Main에 Merge 될 수 있도록 하면 좋을 것 같아요.
브랜치의 경우 현재 엄청 많은데, Main에 Merge된 브랜치의 경우 정리해서 브랜치 관리를 조금 더 깔끔하게 하면 좋을 것 같습니다.
또한 브랜치 명도 특정 전략들이 있는데 찾아보고 적용해보시면 좋을 것 같습니다.

전반적인 코드 관리는 깔끔하게 진행하신 것 같아요.
폴더 구분도 잘 하신 것 같구요.
다만, 불필요한 코드들의 경우 현재 대규모 주석처리가 된 부분들이 있어요.
불필요하다고 판단된 경우 삭제하면 좋을 것 같습니다.
또한, 주석 역시 기능 설명을 위해 많이 적어두셨는데요. 
없어도 충분히 이해할 수 있는 코드들이라 잘 정리해두면 좋을 것 같아요.

추가적으로 API Key 같은 것들을 환경 변수로 숨겨 보면 좋을 것 같아요.
지금은 평문으로 하드코딩되어 있는데 한번 시도해보시면 어렵지 않으니 충분히 가능할 것입니다.
 
고생하셨습니다 :)

**Comment by ooheunda** [comment]
피드백 감사합니다!
